import {
  AUTH_FORGOT_PASSWORD,
  AUTH_LOGIN,
  AUTH_REGISTER,
  AUTH_ROOT,
} from './auth.endpoint';
import {
  ADD_DISABLE_FEATURE,
  DISABLE_FEATURE_LIST,
  ENABLE_FEATURE,
  FEATURE_LIST,
  FEATURE_ROOT,
} from './feature.endpoint';
import {
  LANGUAGE_ADD,
  LANGUAGE_GET_DETAIL,
  LANGUAGE_INPUT,
  LANGUAGE_ROOT,
} from './language.endpoint';
import {
  ACTIVE_PERMISSION,
  ADD_PERMISSION,
  DEACTIVATE_PERMISSION,
  GET_LIST_PERMISSION,
  PERMISSION_DETAIL,
  PERMISSION_ROOT,
  UPDATE_FEATURE_USER_PERMISSION,
  UPDATE_PERMISSION,
} from './permission.endpoint';
import {
  DEACTIVATE_USER,
  USER_ACTIVE,
  USER_GET_LIST,
  USER_INSERT,
  USER_ROOT,
  USER_UPDATE,
} from './user.endpoint';

export const EndpointTree = {
  USER: {
    USER_ROOT,
    USER_GET_LIST,
    USER_INSERT,
    USER_UPDATE,
    USER_ACTIVE,
    DEACTIVATE_USER,
  },
  AUTH: {
    AUTH_ROOT,
    AUTH_FORGOT_PASSWORD,
    AUTH_LOGIN,
    AUTH_REGISTER,
  },
  FEATURE: {
    FEATURE_ROOT,
    ENABLE_FEATURE,
    FEATURE_LIST,
    DISABLE_FEATURE_LIST,
    ADD_DISABLE_FEATURE,
  },
  PERMISSION: {
    PERMISSION_ROOT,
    GET_LIST_PERMISSION,
    ADD_PERMISSION,
    UPDATE_PERMISSION,
    ACTIVE_PERMISSION,
    DEACTIVATE_PERMISSION,
    UPDATE_FEATURE_USER_PERMISSION,
    PERMISSION_DETAIL,
  },
  LANGUAGE: {
    LANGUAGE_ROOT,
    LANGUAGE_GET_DETAIL,
    LANGUAGE_INPUT,
    LANGUAGE_ADD,
  },
};
